Avoid npm dependency-hell by downgrading Handlebars?
The upgrade in 44122a26 may have been the cause of:

```
       [warn] 	Note: Unresolved dependencies path:
       [warn] 		org.webjars.npm:amdefine:0.0.4
       [warn] 		  +- org.webjars.npm:source-map:[0.4.4,0.5)
       [warn] 		  +- org.webjars.npm:handlebars:4.0.6 (/tmp/scala_buildpack_build_dir/build.sbt#L32-49)
       [warn] 		  +- repo-genesis:repo-genesis_2.11:1.0-SNAPSHOT
       sbt.ResolveException: unresolved dependency: org.webjars.npm#amdefine;0.0.4: not found
```

...seen on Heroku but not locally.